app/pages/views.py
from flask import Blueprint, render_template

pages = Blueprint("pages", __name__, template_folder='templates')


@pages.route("/")
def home():
    return render_template("pages/index.html")

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} {{ config['SITE_NAME'] }} {% endblock %}</title>

    {% block head %}
    <!-- Fevicon -->
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon" />
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/all.css') }}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

    {% block page_css %}
    {% endblock %}
</head>

<body>
    {% block header %}
    <header class="mb-4">
        <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
            <div class="container px-2 px-sm-3 px-md-4 py-1">
                <a class="navbar-brand fs-6 px-1 px-sm-2 px-md-3" href="{{ url_for('pages.home') }}">
                    Reshape<span class="font-semi-bold">PDF</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    {% endblock %}

    {% block content %}
    <div class="container px-3 px-md-4 px-lg-5 mb-3">
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        <div id="flash-messages" class="row justify-content-center">
            {% for category, msg in messages %}
            <div class="alert alert-{{ category }} text-center w-auto rounded-3 px-5" role="alert">
                {{ msg }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </div>
    {% endblock %}

    {% block page_content %}
    {% endblock %}

    {% block footer %}
    <footer class="p-4 bg-dark text-center">
        <span class="text-muted">© 2021</span>
        <span class="text-light">Reshape</span>
        <span class="primary-color font-semi-bold">PDF</span>
    </footer>
    {% endblock %}

    {% block script %}
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    <!-- Custom JS -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    {% endblock %}

    {% block page_script %}
    {% endblock %}
</body>

</html>